### ISSUE TITLE
Error : "No module named sksparse.cholmod". Scikit-sparse installation is not working on windows 10.

### ISSUE THREAD

**Issue by sanaafhn** [san-santra/dehaze_t_comparator#1]
I'm using Anaconda 2 on windows 10. I have successfully installed all the other requirements like Keras with Theano, Scikit-image, Scipy and numpy but for some reason Scikit-sparse installation is not working. If I try to run dehaze_im_binsearch.py then I'm getting the error as "No module named sksparse.cholmod". Any help would be appreciated. Thank You.

**Comment by san-santra** [comment]
First of all sksparse is not essential for the code to run. But the problem is scikit sparse matrix solvers are slower than this. 
I am adding another code that works without using the sksparse. 
It will be better if you describe the problem you are facing when trying to install scikit-sparse.
