### ISSUE TITLE
Linux or windows? 

### ISSUE THREAD

**Issue by sanaafhn** [san-santra/dehaze_t_comparator#3]
On which operating system did you run this project? I tried on windows and it doesn't seem to work. Currently trying on Linux using VirtualBox in my windows laptop and I'm getting these warning when I'm trying to execute. All of this new to me and I'm still learning. 
![Capture](https://user-images.githubusercontent.com/44388655/58552732-bfd59f00-8230-11e9-8ffa-dbd839435c3d.PNG)
Please, any help would be very helpful. 
![Capture](https://user-images.githubusercontent.com/44388655/58552759-cb28ca80-8230-11e9-84e6-be8009dcf019.PNG)

**Comment by sanaafhn** [comment]
This is what I'm getting when I'm trying on windows.
![Capture2](https://user-images.githubusercontent.com/44388655/58553104-abde6d00-8231-11e9-8b43-44686e2876b5.PNG)

**Comment by san-santra** [comment]
First of all, in the linux installation within VirtualBox the code is running successfully. The messages are just warnings. After successful run of the code the result is saved in ``out`` directory.
Apart from that, the error you are getting in windows is related to numpy. Try reinstalling numpy using ``conda install``.

**Comment by sanaafhn** [comment]
@san-santra Thank you so much for the help and for the reply. May I know what commands should I enter to display the images/output from out directory in Linux and in Windows? I'm new to Image Processing and programming. I've tried a lot.. any help would be very helpful.

**Comment by san-santra** [comment]
The outputs are stored in the ``out`` directory by default. You can use any image viewer to display them.
